### ISSUE TITLE
Signature in a custom page of the pdf

### ISSUE THREAD

**Issue by i-olivares** [vizicsaba89/pdf-signer#11] opened 2020-06-30 10:10 UTC
Hi, 

would it be possible to place the signature in other page of the document rather than in the first or in the last pages? I'm trying to figure out how but I'm not able to do it. 

Thanks!

**Comment by vizicsaba89** [comment] 2020-07-01 04:32
Hi @i-olivares !

Currently you can only place the signatures either in the first or the last page. We try to add this functionality as soon as possible, so please stay tuned till’ a next release :)

**Comment by i-olivares** [comment] 2020-07-01 16:18
Thanks @vizicsaba89! :) And thanks and congratulations for the great work with the pdf-signer module, it has been really helpful!

**Comment by pankucsi** [comment] 2020-07-03 21:34
Hello @i-olivares,

I had a little refactor in the module, but after we have reviewed it together with @vizicsaba89 , this feature will be available.
We can't guarantee it will be fast, but we will try close it as soon as possible.

If you cant wait, you could checkout the ` throw_out_pdfmockkit ` branch, build it and feel free to use.

**Comment by NoahCardoza** [comment] 2020-10-18 10:59
@pankucsi What exactly is the cause of the slowdown? Are we talking like a giant PDF or even a PDF with < 5 pages?

**Comment by pankucsi** [comment] 2020-10-19 07:56
Unfortunately I don't have enough free time to catch myself up, and I thought if somebody want to use it he can checkout the another branch.

In the other hand I think giant / small pdf should not matters.

**Comment by pankucsi** [comment] 2020-10-19 10:13
I had merged the branches and published a new version. Furthermore the unused and outdated branches have been deleted.

Now you are able to provide an annotationOnPages property in the signatureOptions.

**Closed by pankucsi** 2020-10-19 10:13 UTC
